### ISSUE TITLE
Jenkins pipeline can not find the apk/ipa file to upload 

### ISSUE THREAD

**Issue by Pooriafd** [testproject-io/jenkins-plugin#9]
Hi 
I get this error in pipeline when a path to file is specified and try to use 'tpAppUpdateFile' function in jenkins 
But apparently plugin can not find file despite having file in workspace

when I looked closer to the code it seems you are reading file by path, but it seems that in Jenkins pipeline new File(filePath) doesn't work and readFile function works(probably worth to see how it reads the data)
https://github.com/testproject-io/jenkins-plugin/blob/40691bd3ea5069c4c6c1d632df560e235fe383a9/src/main/java/io/testproject/helpers/FileUploadHelper.java#L29

I was wondering if you can tell me what I'm doing wrong

Regards

**Comment by eldarkra** [comment]
Hello @Pooriafd , Thanks for pointing out.
The issue that you describe has already been fixed and is the next version (2.8) of the plugin is going to be released in the following week.

**Comment by eldarkra** [comment]
Version 2.8 was released and available for download: https://plugins.jenkins.io/testproject/

**Comment by Pooriafd** [comment]
> Version 2.8 was released and available for download: https://plugins.jenkins.io/testproject/

Thanks Eldar!
